# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

RoleType.create(:id => 1, :name => "individual")
RoleType.create(:id => 2, :name=> "business")
JobType.create(:id => 1, :type_title => "ESL JOBS")

Country.create(:id => 1, :countryname => "N/A")
Country.create(:id => 2, :countryname => "Afghanistan")
Country.create(:id => 3, :countryname => "Albania")
Country.create(:id => 4, :countryname => "Algeria")
Country.create(:id => 5, :countryname => "Andorra")
Country.create(:id => 6, :countryname => "Angola")
Country.create(:id => 7, :countryname => "Antigua and Barbuda")
Country.create(:id => 8, :countryname => "Argentina")
Country.create(:id => 9, :countryname => "Armenia")
Country.create(:id => 10, :countryname => "Aruba")
Country.create(:id => 11, :countryname => "Australia")
Country.create(:id => 12, :countryname => "Austria")
Country.create(:id => 13, :countryname => "Azerbaijan")
Country.create(:id => 14, :countryname => "Bahamas")
Country.create(:id => 15, :countryname => "Bahrain")
Country.create(:id => 16, :countryname => "Bangladesh")
Country.create(:id => 17, :countryname => "Barbados")
Country.create(:id => 18, :countryname => "Belarus")
Country.create(:id => 19, :countryname => "Belgium")
Country.create(:id => 20, :countryname => "Belize")
Country.create(:id => 21, :countryname => "Benin")
Country.create(:id => 22, :countryname => "Bhutan")
Country.create(:id => 23, :countryname => "Bolivia")
Country.create(:id => 24, :countryname => "Bosnia and Herzegovina")
Country.create(:id => 25, :countryname => "Botswana")
Country.create(:id => 26, :countryname => "Brazil")
Country.create(:id => 27, :countryname => "Brunei")
Country.create(:id => 28, :countryname => "Bulgaria")
Country.create(:id => 29, :countryname => "Burkina Faso")
Country.create(:id => 30, :countryname => "Burma")
Country.create(:id => 31, :countryname => "Burundi")
Country.create(:id => 32, :countryname => "Cambodia")
Country.create(:id => 33, :countryname => "Cameroon")
Country.create(:id => 34, :countryname => "Canada")
Country.create(:id => 35, :countryname => "Cape Verde")
Country.create(:id => 36, :countryname => "Central African Republic")
Country.create(:id => 37, :countryname => "Chad")
Country.create(:id => 38, :countryname => "Chile")
Country.create(:id => 39, :countryname => "China")
Country.create(:id => 40, :countryname => "Colombia")
Country.create(:id => 41, :countryname => "Comoros")
Country.create(:id => 42, :countryname => "Congo, Democratic Republic of the")
Country.create(:id => 43, :countryname => "Congo, Republic of the")
Country.create(:id => 44, :countryname => "Costa Rica")
Country.create(:id => 45, :countryname => "Cote d'Ivoire")
Country.create(:id => 46, :countryname => "Croatia")
Country.create(:id => 47, :countryname => "Cuba")
Country.create(:id => 48, :countryname => "Curacao")
Country.create(:id => 49, :countryname => "Cyprus")
Country.create(:id => 50, :countryname => "Czech Republic")
Country.create(:id => 51, :countryname => "Denmark")
Country.create(:id => 52, :countryname => "Djibouti")
Country.create(:id => 53, :countryname => "Dominica")
Country.create(:id => 54, :countryname => "Dominican Republic")
Country.create(:id => 55, :countryname => "East Timor (see Timor-Leste)")
Country.create(:id => 56, :countryname => "Ecuador")
Country.create(:id => 57, :countryname => "Egypt")
Country.create(:id => 58, :countryname => "El Salvador")
Country.create(:id => 59, :countryname => "Equatorial Guinea")
Country.create(:id => 60, :countryname => "Eritrea")
Country.create(:id => 61, :countryname => "Estonia")
Country.create(:id => 62, :countryname => "Ethiopia")
Country.create(:id => 63, :countryname => "Fiji")
Country.create(:id => 64, :countryname => "Finland")
Country.create(:id => 65, :countryname => "France")
Country.create(:id => 66, :countryname => "Gabon")
Country.create(:id => 67, :countryname => "Gambia, The")
Country.create(:id => 68, :countryname => "Georgia")
Country.create(:id => 69, :countryname => "Germany")
Country.create(:id => 70, :countryname => "Ghana")
Country.create(:id => 71, :countryname => "Greece")
Country.create(:id => 72, :countryname => "Grenada")
Country.create(:id => 73, :countryname => "Guatemala")
Country.create(:id => 74, :countryname => "Guinea")
Country.create(:id => 75, :countryname => "Guinea-Bissau")
Country.create(:id => 76, :countryname => "Guyana")
Country.create(:id => 77, :countryname => "Haiti")
Country.create(:id => 78, :countryname => "Holy See")
Country.create(:id => 79, :countryname => "Honduras")
Country.create(:id => 80, :countryname => "Hong Kong")
Country.create(:id => 81, :countryname => "Hungary")
Country.create(:id => 82, :countryname => "Iceland")
Country.create(:id => 83, :countryname => "India")
Country.create(:id => 84, :countryname => "Indonesia")
Country.create(:id => 85, :countryname => "Iran")
Country.create(:id => 86, :countryname => "Iraq")
Country.create(:id => 87, :countryname => "Ireland")
Country.create(:id => 88, :countryname => "Israel")
Country.create(:id => 89, :countryname => "Italy")
Country.create(:id => 90, :countryname => "Jamaica")
Country.create(:id => 91, :countryname => "Japan")
Country.create(:id => 92, :countryname => "Jordan")
Country.create(:id => 93, :countryname => "Kazakhstan")
Country.create(:id => 94, :countryname => "Kenya")
Country.create(:id => 95, :countryname => "Kiribati")
Country.create(:id => 96, :countryname => "Korea, North")
Country.create(:id => 97, :countryname => "Korea, South")
Country.create(:id => 98, :countryname => "Kosovo")
Country.create(:id => 99, :countryname => "Kuwait")
Country.create(:id => 100, :countryname => "Kyrgyzstan")
Country.create(:id => 101, :countryname => "Laos")
Country.create(:id => 102, :countryname => "Latvia")
Country.create(:id => 103, :countryname => "Lebanon")
Country.create(:id => 104, :countryname => "Lesotho")
Country.create(:id => 105, :countryname => "Liberia")
Country.create(:id => 106, :countryname => "Libya")
Country.create(:id => 107, :countryname => "Liechtenstein")
Country.create(:id => 108, :countryname => "Lithuania")
Country.create(:id => 109, :countryname => "Luxembourg")
Country.create(:id => 110, :countryname => "Macau")
Country.create(:id => 111, :countryname => "Macedonia")
Country.create(:id => 112, :countryname => "Madagascar")
Country.create(:id => 113, :countryname => "Malawi")
Country.create(:id => 114, :countryname => "Malaysia")
Country.create(:id => 115, :countryname => "Maldives")
Country.create(:id => 116, :countryname => "Mali")
Country.create(:id => 117, :countryname => "Malta")
Country.create(:id => 118, :countryname => "Marshall Islands")
Country.create(:id => 119, :countryname => "Mauritania")
Country.create(:id => 120, :countryname => "Mauritius")
Country.create(:id => 121, :countryname => "Mexico")
Country.create(:id => 122, :countryname => "Micronesia")
Country.create(:id => 123, :countryname => "Moldova")
Country.create(:id => 124, :countryname => "Monaco")
Country.create(:id => 125, :countryname => "Mongolia")
Country.create(:id => 126, :countryname => "Montenegro")
Country.create(:id => 127, :countryname => "Morocco")
Country.create(:id => 128, :countryname => "Mozambique")
Country.create(:id => 129, :countryname => "Namibia")
Country.create(:id => 130, :countryname => "Nauru")
Country.create(:id => 131, :countryname => "Nepal")
Country.create(:id => 132, :countryname => "Netherlands")
Country.create(:id => 133, :countryname => "Netherlands Antilles")
Country.create(:id => 134, :countryname => "New Zealand")
Country.create(:id => 135, :countryname => "Nicaragua")
Country.create(:id => 136, :countryname => "Niger")
Country.create(:id => 137, :countryname => "Nigeria")
Country.create(:id => 138, :countryname => "North Korea")
Country.create(:id => 139, :countryname => "Norway")
Country.create(:id => 140, :countryname => "Oman")
Country.create(:id => 141, :countryname => "Pakistan")
Country.create(:id => 142, :countryname => "Palau")
Country.create(:id => 143, :countryname => "Palestinian Territories")
Country.create(:id => 144, :countryname => "Panama")
Country.create(:id => 145, :countryname => "Papua New Guinea")
Country.create(:id => 146, :countryname => "Paraguay")
Country.create(:id => 147, :countryname => "Peru")
Country.create(:id => 148, :countryname => "Philippines")
Country.create(:id => 149, :countryname => "Poland")
Country.create(:id => 150, :countryname => "Portugal")
Country.create(:id => 151, :countryname => "Qatar")
Country.create(:id => 152, :countryname => "Romania")
Country.create(:id => 153, :countryname => "Russia")
Country.create(:id => 154, :countryname => "Rwanda")
Country.create(:id => 155, :countryname => "Saint Kitts and Nevis")
Country.create(:id => 156, :countryname => "Saint Lucia")
Country.create(:id => 157, :countryname => "Saint Vincent and the Grenadines")
Country.create(:id => 158, :countryname => "Samoa")
Country.create(:id => 159, :countryname => "San Marino")
Country.create(:id => 160, :countryname => "Sao Tome and Principe")
Country.create(:id => 161, :countryname => "Saudi Arabia")
Country.create(:id => 162, :countryname => "Senegal")
Country.create(:id => 163, :countryname => "Serbia")
Country.create(:id => 164, :countryname => "Seychelles")
Country.create(:id => 165, :countryname => "Sierra Leone")
Country.create(:id => 166, :countryname => "Singapore")
Country.create(:id => 167, :countryname => "Sint Maarten")
Country.create(:id => 168, :countryname => "Slovakia")
Country.create(:id => 169, :countryname => "Slovenia")
Country.create(:id => 170, :countryname => "Solomon Islands")
Country.create(:id => 171, :countryname => "Somalia")
Country.create(:id => 172, :countryname => "South Africa")
Country.create(:id => 173, :countryname => "South Korea")
Country.create(:id => 174, :countryname => "South Sudan")
Country.create(:id => 175, :countryname => "Spain")
Country.create(:id => 176, :countryname => "Sri Lanka")
Country.create(:id => 177, :countryname => "Sudan")
Country.create(:id => 178, :countryname => "Suriname")
Country.create(:id => 179, :countryname => "Swaziland")
Country.create(:id => 180, :countryname => "Sweden")
Country.create(:id => 181, :countryname => "Switzerland")
Country.create(:id => 182, :countryname => "Syria")
Country.create(:id => 183, :countryname => "Taiwan")
Country.create(:id => 184, :countryname => "Tajikistan")
Country.create(:id => 185, :countryname => "Tanzania")
Country.create(:id => 186, :countryname => "Thailand")
Country.create(:id => 187, :countryname => "Timor-Leste")
Country.create(:id => 189, :countryname => "Togo")
Country.create(:id => 190, :countryname => "Tonga")
Country.create(:id => 191, :countryname => "Trinidad and Tobago")
Country.create(:id => 192, :countryname => "Tunisia")
Country.create(:id => 193, :countryname => "Turkey")
Country.create(:id => 194, :countryname => "Turkmenistan")
Country.create(:id => 195, :countryname => "Tuvalu")
Country.create(:id => 196, :countryname => "Uganda")
Country.create(:id => 197, :countryname => "Ukraine")
Country.create(:id => 198, :countryname => "United Arab Emirates")
Country.create(:id => 199, :countryname => "United Kingdom")
Country.create(:id => 200, :countryname => "Uruguay")
Country.create(:id => 201, :countryname => "Uzbekistan")
Country.create(:id => 202, :countryname => "Vanuatu")
Country.create(:id => 203, :countryname => "Venezuela")
Country.create(:id => 204, :countryname => "Vietnam")
Country.create(:id => 205, :countryname => "Yemen")
Country.create(:id => 206, :countryname => "Zambia")
Country.create(:id => 207, :countryname => "Zimbabwe")

# Country.create(:id => 1, :countryname => "Afghanistan")
# Country.create(:id => 2, :countryname => "Åland Islands")
# Country.create(:id => 3, :countryname => "Albania")
# Country.create(:id => 4, :countryname => "Algeria")
# Country.create(:id => 5, :countryname => "American Samoa")
# Country.create(:id => 6, :countryname => "Andorra")
# Country.create(:id => 7, :countryname => "Angola")
# Country.create(:id => 8, :countryname => "Anguilla")
# Country.create(:id => 9, :countryname => "Antarctica")
# Country.create(:id => 10, :countryname => "Antigua And Barbuda")
# Country.create(:id => 11, :countryname => "Argentina")
# Country.create(:id => 12, :countryname => "Armenia")
# Country.create(:id => 13, :countryname => "Aruba")
# Country.create(:id => 14, :countryname => "Australia")
# Country.create(:id => 15, :countryname => "Austria")
# Country.create(:id => 16, :countryname => "Azerbaijan")
# Country.create(:id => 17, :countryname => "Bahamas")
# Country.create(:id => 18, :countryname => "Bahrain")
# Country.create(:id => 19, :countryname => "Bangladesh")
# Country.create(:id => 20, :countryname => "Barbados")
# Country.create(:id => 21, :countryname => "Belarus")
# Country.create(:id => 22, :countryname => "Belgium")
# Country.create(:id => 23, :countryname => "Belize")
# Country.create(:id => 24, :countryname => "Benin")
# Country.create(:id => 25, :countryname => "Bermuda")
# Country.create(:id => 26, :countryname => "Bhutan")
# Country.create(:id => 27, :countryname => "Bolivia")
# Country.create(:id => 28, :countryname => "Bonaire, Sint Eustatius and Saba")
# Country.create(:id => 29, :countryname => "Bosnia and Herzegovina")
# Country.create(:id => 30, :countryname => "Botswana")
# Country.create(:id => 31, :countryname => "Bouvet Island")
# Country.create(:id => 32, :countryname => "Brazil")
# Country.create(:id => 33, :countryname => "British Indian Ocean Territory")
# Country.create(:id => 34, :countryname => "Brunei Darussalam")
# Country.create(:id => 35, :countryname => "Bulgaria")
# Country.create(:id => 36, :countryname => "Burkina Faso")
# Country.create(:id => 37, :countryname => "Burundi")
# Country.create(:id => 38, :countryname => "Cambodia")
# Country.create(:id => 39, :countryname => "Cameroon")
# Country.create(:id => 40, :countryname => "Canada")
# Country.create(:id => 41, :countryname => "Cape Verde")
# Country.create(:id => 42, :countryname => "Cayman Islands")
# Country.create(:id => 43, :countryname => "Central African Republic")
# Country.create(:id => 44, :countryname => "Chad")
# Country.create(:id => 45, :countryname => "Chile")
# Country.create(:id => 46, :countryname => "China")
# Country.create(:id => 47, :countryname => "Christmas Island")
# Country.create(:id => 48, :countryname => "Cocos (Keeling) Islands")
# Country.create(:id => 49, :countryname => "Colombia")
# Country.create(:id => 50, :countryname => "Comoros")
# Country.create(:id => 51, :countryname => "Congo")
# Country.create(:id => 52, :countryname => "Congo, the Democratic Republic of the")
# Country.create(:id => 53, :countryname => "Cook Islands")
# Country.create(:id => 54, :countryname => "Costa Rica")
# Country.create(:id => 55, :countryname => "Côte d'Ivoire")
# Country.create(:id => 56, :countryname => "Croatia")
# Country.create(:id => 57, :countryname => "Cuba")
# Country.create(:id => 58, :countryname => "Curaçao")
# Country.create(:id => 59, :countryname => "Cyprus")
# Country.create(:id => 60, :countryname => "Czech Republic")
# Country.create(:id => 61, :countryname => "Denmark")
# Country.create(:id => 62, :countryname => "Djibouti")
# Country.create(:id => 63, :countryname => "Dominica")
# Country.create(:id => 64, :countryname => "Dominican Republic")
# Country.create(:id => 65, :countryname => "Ecuador")
# Country.create(:id => 66, :countryname => "Egypt")
# Country.create(:id => 67, :countryname => "El Salvador")
# Country.create(:id => 68, :countryname => "Equatorial Guinea")
# Country.create(:id => 69, :countryname => "Eritrea")
# Country.create(:id => 70, :countryname => "Estonia")
# Country.create(:id => 71, :countryname => "Ethiopia")
# Country.create(:id => 72, :countryname => "Falkland Islands (Malvinas)")
# Country.create(:id => 73, :countryname => "Faroe Islands")
# Country.create(:id => 74, :countryname => "Fiji")
# Country.create(:id => 75, :countryname => "Finland")
# Country.create(:id => 76, :countryname => "France")
# Country.create(:id => 77, :countryname => "French Guiana")
# Country.create(:id => 78, :countryname => "French Polynesia")
# Country.create(:id => 79, :countryname => "French Southern Territories")
# Country.create(:id => 80, :countryname => "Gabon")
# Country.create(:id => 81, :countryname => "Gambia")
# Country.create(:id => 82, :countryname => "Georgia")
# Country.create(:id => 83, :countryname => "Germany")
# Country.create(:id => 84, :countryname => "Ghana")
# Country.create(:id => 85, :countryname => "Gibraltar")
# Country.create(:id => 86, :countryname => "Greece")
# Country.create(:id => 87, :countryname => "Greenland")
# Country.create(:id => 88, :countryname => "Grenada")
# Country.create(:id => 89, :countryname => "Guadeloupe")
# Country.create(:id => 90, :countryname => "Guam")
# Country.create(:id => 91, :countryname => "Guatemala")
# Country.create(:id => 92, :countryname => "Guernsey")
# Country.create(:id => 93, :countryname => "Guinea")
# Country.create(:id => 94, :countryname => "Guinea-Bissau")
# Country.create(:id => 95, :countryname => "Guyana")
# Country.create(:id => 96, :countryname => "Haiti")
# Country.create(:id => 97, :countryname => "Heard Island and McDonald Islands")
# Country.create(:id => 98, :countryname => "Holy See (Vatican City State)")
# Country.create(:id => 99, :countryname => "Honduras")
# Country.create(:id => 100, :countryname => "Hong Kong")
# Country.create(:id => 101, :countryname => "Hungary")
# Country.create(:id => 102, :countryname => "Iceland")
# Country.create(:id => 103, :countryname => "India")
# Country.create(:id => 104, :countryname => "Indonesia")
# Country.create(:id => 105, :countryname => "Iran, Islamic Republic of")
# Country.create(:id => 106, :countryname => "Iraq")
# Country.create(:id => 107, :countryname => "Ireland")
# Country.create(:id => 108, :countryname => "Isle of Man")
# Country.create(:id => 109, :countryname => "Israel")
# Country.create(:id => 110, :countryname => "Italy")
# Country.create(:id => 111, :countryname => "Jamaica")
# Country.create(:id => 112, :countryname => "Japan")
# Country.create(:id => 113, :countryname => "Jersey")
# Country.create(:id => 114, :countryname => "Jordan")
# Country.create(:id => 115, :countryname => "Kazakhstan")
# Country.create(:id => 116, :countryname => "Kenya")
# Country.create(:id => 117, :countryname => "Kiribati")
# Country.create(:id => 118, :countryname => "Korea, Democratic People's Republic of")
# Country.create(:id => 119, :countryname => "Korea, Republic of")
# Country.create(:id => 120, :countryname => "Kuwait")
# Country.create(:id => 121, :countryname => "Kyrgyzstan")
# Country.create(:id => 122, :countryname => "Lao People's Democratic Republic")
# Country.create(:id => 123, :countryname => "Latvia")
# Country.create(:id => 124, :countryname => "Lebanon")
# Country.create(:id => 125, :countryname => "Lesotho")
# Country.create(:id => 126, :countryname => "Liberia")
# Country.create(:id => 127, :countryname => "Libyan Arab Jamahiriya")
# Country.create(:id => 128, :countryname => "Liechtenstein")
# Country.create(:id => 129, :countryname => "Lithuania")
# Country.create(:id => 130, :countryname => "Luxembourg")
# Country.create(:id => 131, :countryname => "Macao")
# Country.create(:id => 132, :countryname => "Macedonia, The Former Yugoslav Republic Of")
# Country.create(:id => 133, :countryname => "Madagascar")
# Country.create(:id => 134, :countryname => "Malawi")
# Country.create(:id => 135, :countryname => "Malaysia")
# Country.create(:id => 136, :countryname => "Maldives")
# Country.create(:id => 137, :countryname => "Mali")
# Country.create(:id => 138, :countryname => "Malta")
# Country.create(:id => 139, :countryname => "Marshall Islands")
# Country.create(:id => 140, :countryname => "Martinique")
# Country.create(:id => 141, :countryname => "Mauritania")
# Country.create(:id => 142, :countryname => "Mauritius")
# Country.create(:id => 143, :countryname => "Mayotte")
# Country.create(:id => 144, :countryname => "Mexico")
# Country.create(:id => 145, :countryname => "Micronesia, Federated States of")
# Country.create(:id => 146, :countryname => "Moldova, Republic of")
# Country.create(:id => 147, :countryname => "Monaco")
# Country.create(:id => 148, :countryname => "Mongolia")
# Country.create(:id => 149, :countryname => "Montenegro")
# Country.create(:id => 150, :countryname => "Montserrat")
# Country.create(:id => 151, :countryname => "Morocco")
# Country.create(:id => 152, :countryname => "Mozambique")
# Country.create(:id => 153, :countryname => "Myanmar")
# Country.create(:id => 154, :countryname => "Namibia")
# Country.create(:id => 155, :countryname => "Nauru")
# Country.create(:id => 156, :countryname => "Nepal")
# Country.create(:id => 157, :countryname => "Netherlands")
# Country.create(:id => 158, :countryname => "New Caledonia")
# Country.create(:id => 159, :countryname => "New Zealand")
# Country.create(:id => 160, :countryname => "Nicaragua")
# Country.create(:id => 161, :countryname => "Niger")
# Country.create(:id => 162, :countryname => "Nigeria")
# Country.create(:id => 163, :countryname => "Niue")
# Country.create(:id => 164, :countryname => "Norfolk Island")
# Country.create(:id => 165, :countryname => "Northern Mariana Islands")
# Country.create(:id => 166, :countryname => "Norway")
# Country.create(:id => 167, :countryname => "Oman")
# Country.create(:id => 168, :countryname => "Pakistan")
# Country.create(:id => 169, :countryname => "Palau")
# Country.create(:id => 170, :countryname => "Palestinian Territory, Occupied")
# Country.create(:id => 171, :countryname => "Panama")
# Country.create(:id => 172, :countryname => "Papua New Guinea")
# Country.create(:id => 173, :countryname => "Paraguay")
# Country.create(:id => 174, :countryname => "Peru")
# Country.create(:id => 175, :countryname => "Philippines")
# Country.create(:id => 176, :countryname => "Pitcairn")
# Country.create(:id => 177, :countryname => "Poland")
# Country.create(:id => 178, :countryname => "Portugal")
# Country.create(:id => 179, :countryname => "Puerto Rico")
# Country.create(:id => 180, :countryname => "Qatar")
# Country.create(:id => 181, :countryname => "Réunion")
# Country.create(:id => 182, :countryname => "Romania")
# Country.create(:id => 183, :countryname => "Russian Federation")
# Country.create(:id => 184, :countryname => "Rwanda")
# Country.create(:id => 185, :countryname => "Saint Barthélemy")
# Country.create(:id => 186, :countryname => "Saint Helena")
# Country.create(:id => 187, :countryname => "Saint Kitts and Nevis")
# Country.create(:id => 188, :countryname => "Saint Lucia")
# Country.create(:id => 189, :countryname => "Saint Martin (French Part)")
# Country.create(:id => 190, :countryname => "Saint Pierre and Miquelon")
# Country.create(:id => 191, :countryname => "Saint Vincent and the Grenadines")
# Country.create(:id => 192, :countryname => "Samoa")
# Country.create(:id => 193, :countryname => "San Marino")
# Country.create(:id => 194, :countryname => "Sao Tome and Principe")
# Country.create(:id => 195, :countryname => "Saudi Arabia")
# Country.create(:id => 196, :countryname => "Senegal")
# Country.create(:id => 197, :countryname => "Serbia")
# Country.create(:id => 198, :countryname => "Seychelles")
# Country.create(:id => 199, :countryname => "Sierra Leone")
# Country.create(:id => 200, :countryname => "Singapore")
# Country.create(:id => 201, :countryname => "Sint Maarten (Dutch Part)")
# Country.create(:id => 202, :countryname => "Slovakia")
# Country.create(:id => 203, :countryname => "Slovenia")
# Country.create(:id => 204, :countryname => "Solomon Islands")
# Country.create(:id => 205, :countryname => "Somalia")
# Country.create(:id => 206, :countryname => "South Africa")
# Country.create(:id => 207, :countryname => "South Georgia and the South Sandwich Islands")
# Country.create(:id => 208, :countryname => "South Sudan")
# Country.create(:id => 209, :countryname => "Spain")
# Country.create(:id => 210, :countryname => "Sri Lanka")
# Country.create(:id => 211, :countryname => "Sudan")
# Country.create(:id => 212, :countryname => "Suriname")
# Country.create(:id => 213, :countryname => "Svalbard and Jan Mayen")
# Country.create(:id => 214, :countryname => "Swaziland")
# Country.create(:id => 215, :countryname => "Sweden")
# Country.create(:id => 216, :countryname => "Switzerland")
# Country.create(:id => 217, :countryname => "Syrian Arab Republic")
# Country.create(:id => 218, :countryname => "Taiwan, Province of China")
# Country.create(:id => 219, :countryname => "Tajikistan")
# Country.create(:id => 220, :countryname => "Tanzania, United Republic of")
# Country.create(:id => 221, :countryname => "Thailand")
# Country.create(:id => 222, :countryname => "Timor-Leste")
# Country.create(:id => 223, :countryname => "Togo")
# Country.create(:id => 224, :countryname => "Tokelau")
# Country.create(:id => 225, :countryname => "Tonga")
# Country.create(:id => 226, :countryname => "Trinidad and Tobago")
# Country.create(:id => 227, :countryname => "Tunisia")
# Country.create(:id => 228, :countryname => "Turkey")
# Country.create(:id => 229, :countryname => "Turkmenistan")
# Country.create(:id => 230, :countryname => "Turks and Caicos Islands")
# Country.create(:id => 231, :countryname => "Tuvalu")
# Country.create(:id => 232, :countryname => "Uganda")
# Country.create(:id => 233, :countryname => "Ukraine")
# Country.create(:id => 234, :countryname => "United Arab Emirates")
# Country.create(:id => 235, :countryname => "United Kingdom")
# Country.create(:id => 236, :countryname => "United States")
# Country.create(:id => 237, :countryname => "United States Minor Outlying Islands")
# Country.create(:id => 238, :countryname => "Uruguay")
# Country.create(:id => 239, :countryname => "Uzbekistan")
# Country.create(:id => 240, :countryname => "Vanuatu")
# Country.create(:id => 241, :countryname => "Venezuela")
# Country.create(:id => 242, :countryname => "Vietnam")
# Country.create(:id => 243, :countryname => "Virgin Islands, British")
# Country.create(:id => 244, :countryname => "Virgin Islands, U.S.")
# Country.create(:id => 245, :countryname => "Wallis and Futuna")
# Country.create(:id => 246, :countryname => "Western Sahara")
# Country.create(:id => 247, :countryname => "Yemen")
# Country.create(:id => 248, :countryname => "Zambia")
# Country.create(:id => 249, :countryname => "Zimbabwe")
# Country.create(:id => 250, :countryname => "International")
# Country.create(:id => 251, :countryname => "Oceania")